services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:8080:8080"
  scaffold-manager:
    image: "scaffold:test"
    restart: always
    ports:
      - "127.0.0.1:2997:2997"
    environment:
      SCAFFOLD_KILL_SERVER_PORT: "19999"
      SCAFFOLD_RUN_MODE: "test"
      SCAFFOLD_BASE_URL: http://scaffold-manager:2997
      SCAFFOLD_LOG_LEVEL: "INFO"
      SCAFFOLD_LOG_FORMAT: "console"
      SCAFFOLD_SLEEP: "30"
      SCAFFOLD_ADMIN: |
        {
          "username": "admin",
          "password": "admin"
        }
      SCAFFOLD_DB_CONNECTION_STRING: "mongodb://MyCoolMongoDBUsername:MyCoolMongoDBPassword@mongodb:27017/scaffold"
      SCAFFOLD_NODE: |
        {
          "type": "manager",
          "manager_host": "scaffold-manager",
          "manager_port": 2997,
          "join_key": "MyCoolJoinKey12345",
          "primary_key": "MyCoolPrimaryKey12345",
          "manager_protocol": "http"
        }
      SCAFFOLD_FILESTORE: |
        {
          "access_key": "MyCoolMinIOAccessKey",
          "secret_key": "MyCoolMinIOSecretKey",
          "host": "minio",
          "port": 9090,
          "bucket": "scaffold",
          "region": "default-region",
          "protocol": "http",
          "type": "s3"
        }
      RUN_PRUNE_CRON: "*/5 * * * * *"
      RUN_PRUNE_DURATION: "1"
    depends_on:
      - "mongodb"
      - "minio"
      - rabbitmq
    tty: true
  scaffold-worker:
    image: "scaffold:test"
    restart: always
    ports:
      - "127.0.0.1:2998:2998"
    environment:
      SCAFFOLD_KILL_SERVER_PORT: "29999"
      SCAFFOLD_RUN_MODE: "test"
      SCAFFOLD_BASE_URL: http://scaffold-worker:2998
      SCAFFOLD_WS_PORT: "8081"
      SCAFFOLD_LOG_LEVEL: "TRACE"
      SCAFFOLD_LOG_FORMAT: "console"
      SCAFFOLD_ADMIN: |
        {
          "username": "admin",
          "password": "admin"
        }
      SCAFFOLD_SLEEP: "30"
      SCAFFOLD_DB_CONNECTION_STRING: "mongodb://MyCoolMongoDBUsername:MyCoolMongoDBPassword@mongodb:27017/scaffold"
      SCAFFOLD_NODE: |
        {
          "type": "worker",
          "manager_host": "scaffold-manager",
          "manager_port": 2997,
          "join_key": "MyCoolJoinKey12345",
          "primary_key": "MyCoolPrimaryKey12345",
          "manager_protocol": "http"
        }
      SCAFFOLD_FILESTORE: |
        {
          "access_key": "MyCoolMinIOAccessKey",
          "secret_key": "MyCoolMinIOSecretKey",
          "host": "minio",
          "port": 9090,
          "bucket": "scaffold",
          "region": "default-region",
          "protocol": "http",
          "type": "s3"
        }
      SCAFFOLD_RESTART_PERIOD: 10
    depends_on:
      - "scaffold-manager"
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
  mongodb:
    image: centos/mongodb-36-centos7:1
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGODB_DATABASE: scaffold
      MONGODB_ADMIN_PASSWORD: MyCoolAdminPassword
      MONGODB_USER: MyCoolMongoDBUsername
      MONGODB_PASSWORD: MyCoolMongoDBPassword
  minio:
    image: bitnami/minio:2023
    ports:
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:9091:9091"
    environment:
      BITNAMI_DEBUG: "false"
      MINIO_REGION: "default-region"
      MINIO_ROOT_USER: MyCoolMinIOAccessKey
      MINIO_ROOT_PASSWORD: MyCoolMinIOSecretKey
      MINIO_CONSOLE_PORT_NUMBER: "9091"
      MINIO_SERVER_PORT_NUMBER: "9090"
      MINIO_API_PORT_NUMBER: "9090"
