import os

SCAFFOLD_PROTOCOL=os.getenv('SCAFFOLD_PROTOCOL')
SCAFFOLD_HOST="localhost"
SCAFFOLD_PORT=2997
SCAFFOLD_WS_PORT=8080
SCAFFOLD_PRIMARY_KEY="MyCoolPrimaryKey12345"
SCAFFOLD_CLI="../../dist/linux/amd64/scaffold"
