apiVersion: batch/v1
kind: Job
metadata:
  name: scaffold-worker-{{ .RunID }}-{{ .Step }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: scaffold-worker
        image: {{ .WorkerImage }}
        imagePullPolicy: {{ .ImagePullPolicy }}
        command: ["/bin/sh"]
        args: ["-c", "cd /tmp && cp /tmp/scaffold/.executor.sh .executor.sh && cp /tmp/scaffold/.header.py .header.py && cp /tmp/scaffold/.header.sh .header.sh && chmod +x .executor.sh && ./.executor.sh"]
        env:
          - name: SCAFFOLD_LANGUAGE
            value: '{{ .Language }}'
          - name: SCAFFOLD_RESOURCE_TYPES
            value: '{{ .ResourceTypes }}'
          - name: SCAFFOLD_RESOURCES
            value: '{{ .Resources }}'
          - name: SCAFFOLD_INPUTS
            value: '{{ .Inputs }}'
          - name: SCAFFOLD_OUTPUTS
            value: '{{ .Outputs }}'
          - name: SCAFFOLD_SCRIPT
            value: '{{ .Script }}'
          - name: SCAFFOLD_PATH
            value: '{{ .Path }}'
          - name: SCAFFOLD_CONTEXT_b64
            value: '{{ .Context }}'
          - name: SCAFFOLD_PYTHON_REQUIREMENTS
            value: '{{ .PythonRequirements }}'
          - name: LOG_LEVEL
            value: '{{ .LogLevel }}'
        volumeMounts:
        - name: scaffold-volume
          mountPath: /tmp/scaffold
      volumes:
        - name: scaffold-volume
          configMap:
            name: scaffold-scripts
  backoffLimit: 0
