// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "John Carter",
            "url": "https://github.com/jfcarter2358/scaffold/issues",
            "email": "jfcarter2358@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/license/mit/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/datastore": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all datastores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "datastore"
                ],
                "summary": "Get all datastores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/datastore.DataStore"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a datastore from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "datastore"
                ],
                "summary": "Create a datastore",
                "parameters": [
                    {
                        "description": "DataStore Data",
                        "name": "datastore",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/datastore.DataStore"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/datastore/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a datastore by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "datastore"
                ],
                "summary": "Get a datastore",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/datastore.DataStore"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a datastore from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "datastore"
                ],
                "summary": "Update a datastore",
                "parameters": [
                    {
                        "description": "DataStore Data",
                        "name": "datastore",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/datastore.DataStore"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a datastore by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "datastore"
                ],
                "summary": "Delete a datastore",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/file": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "file"
                ],
                "summary": "Get all files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/filestore.ObjectMetadata"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/file/{datastore_name}": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Upload a file to a workflow",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "file"
                ],
                "summary": "Upload a file",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/v1/file/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get files by workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "file"
                ],
                "summary": "Get files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/filestore.ObjectMetadata"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/file/{workflow_name}/{file_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get file by workflow and name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "file"
                ],
                "summary": "Get file",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/filestore.ObjectMetadata"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/file/{workflow_name}/{file_name}/download": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Download a file from a workflow",
                "produces": [
                    "application/text"
                ],
                "tags": [
                    "manager",
                    "file"
                ],
                "summary": "Download a file",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/v1/history/{run_id}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a run history by a run ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "history"
                ],
                "summary": "Get a history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/history.History"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/input": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all inputs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Get all inputs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/input.Input"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a input from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Create a input",
                "parameters": [
                    {
                        "description": "Input Data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/input.Input"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/input/{input_name}": {
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a input by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Delete a input",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/input/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get inputs by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Get inputs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/input.Input"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete inputs by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Delete inputs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/input/{workflow_name}/update": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Trigger updates of states for dependent tasks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Trigger update to dependent tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/input/{workflow_name}/{input_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a input by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Get a input",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/input.Input"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a input from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "input"
                ],
                "summary": "Update a input",
                "parameters": [
                    {
                        "description": "Input Data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/input.Input"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/kill/{workflow_name}/{task_name}": {
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Kill a run on a worker",
                "tags": [
                    "worker",
                    "run"
                ],
                "summary": "Kill a run",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/v1/run/{run_id}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get status of a run by ID",
                "tags": [
                    "manager",
                    "run"
                ],
                "summary": "Get run status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/run/{workflow_name}/{task_name}": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a run from a workflow and task",
                "tags": [
                    "manager",
                    "run"
                ],
                "summary": "Create a run",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/run/{workflow_name}/{task_name}/{task_number}": {
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Instruct a manager to kill a run",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "run"
                ],
                "summary": "Kill a run",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/state": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all states",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Get all states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/state.State"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a state from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Create a state",
                "parameters": [
                    {
                        "description": "State Data",
                        "name": "state",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/state.State"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/state/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get states by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Get states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/state.State"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete states by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Delete states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/state/{workflow_name}/{state_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a state by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Get a state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/state.State"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a state from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Update a state",
                "parameters": [
                    {
                        "description": "State Data",
                        "name": "state",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/state.State"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a state by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "state"
                ],
                "summary": "Delete a state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/task": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all tasks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Get all tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/task.Task"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a task from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Create a task",
                "parameters": [
                    {
                        "description": "Task Data",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.Task"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{task_name}": {
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a task by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Delete a task",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get tasks by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Get tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/task.Task"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete tasks by their workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Delete tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{workflow_name}/{task_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a task by its name and its workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Get a task",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/task.Task"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a task from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Update a task",
                "parameters": [
                    {
                        "description": "Task Data",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.Task"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{workflow_name}/{task_name}/enabled": {
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a task from a JSON object",
                "tags": [
                    "manager",
                    "task"
                ],
                "summary": "Update a task",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.User"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a user from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Create a user",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{user_name}": {
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a user from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Update a user",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{username}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a user by its username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Get a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.User"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a user by its username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Delete a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/webhook/{workflow_name}/{webhook_id}": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Trigger a webhook with optional input data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "webhook"
                ],
                "summary": "Trigger a webhook",
                "parameters": [
                    {
                        "description": "Webhook input Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/workflow": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get all workflows",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "workflow"
                ],
                "summary": "Get all workflows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/workflow.Workflow"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Create a workflow from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "workflow"
                ],
                "summary": "Create a workflow",
                "parameters": [
                    {
                        "description": "Workflow Data",
                        "name": "workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workflow.Workflow"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/workflow/{workflow_name}": {
            "get": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Get a workflow by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "workflow"
                ],
                "summary": "Get a workflow",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workflow.Workflow"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Update a workflow from a JSON object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "workflow"
                ],
                "summary": "Update a workflow",
                "parameters": [
                    {
                        "description": "Workflow Data",
                        "name": "workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workflow.Workflow"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Delete a workflow by its name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "workflow"
                ],
                "summary": "Delete a workflow",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/token/{username}/{token_name}": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Generate an API token for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Generate API Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Revoke an API token for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "manager",
                    "user"
                ],
                "summary": "Revoke API Token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/health/available": {
            "get": {
                "description": "Get status from node succeeding if not containers are running",
                "tags": [
                    "worker",
                    "health"
                ],
                "summary": "Check if a worker node is available",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/health/healthy": {
            "get": {
                "description": "Get node health",
                "tags": [
                    "manager",
                    "worker",
                    "health"
                ],
                "summary": "Check if a node is healthy",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        },
        "/health/ping/{name}": {
            "post": {
                "security": [
                    {
                        "X-Scaffold-API": []
                    }
                ],
                "description": "Ping manager to reset node age",
                "tags": [
                    "manager",
                    "health"
                ],
                "summary": "Ping manager",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Get node readiness",
                "tags": [
                    "manager",
                    "worker",
                    "health"
                ],
                "summary": "Check if a node is ready",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "503": {
                        "description": "Service Unavailable"
                    }
                }
            }
        }
    },
    "definitions": {
        "datastore.DataStore": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        },
        "filestore.ObjectMetadata": {
            "type": "object",
            "properties": {
                "modified": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "history.History": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "states": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/state.State"
                    }
                },
                "updated": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "input.Input": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "state.State": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "disabled": {
                    "type": "boolean"
                },
                "display": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "finished": {
                    "type": "string"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "killed": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "output": {
                    "type": "string"
                },
                "output_checksum": {
                    "type": "string"
                },
                "pid": {
                    "type": "integer"
                },
                "started": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task": {
                    "type": "string"
                },
                "worker": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "task.Task": {
            "type": "object",
            "properties": {
                "auto_execute": {
                    "type": "boolean"
                },
                "container_login_command": {
                    "description": "Check                 TaskCheck         ` + "`" + `json:\"check\" bson:\"check\" yaml:\"check\"` + "`" + `",
                    "type": "string"
                },
                "cron": {
                    "type": "string"
                },
                "depends_on": {
                    "$ref": "#/definitions/task.TaskDependsOn"
                },
                "disabled": {
                    "type": "boolean"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "image": {
                    "type": "string"
                },
                "inputs": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "load": {
                    "$ref": "#/definitions/task.TaskLoadStore"
                },
                "name": {
                    "type": "string"
                },
                "run": {
                    "type": "string"
                },
                "run_number": {
                    "type": "integer"
                },
                "should_rm": {
                    "type": "boolean"
                },
                "store": {
                    "$ref": "#/definitions/task.TaskLoadStore"
                },
                "updated": {
                    "type": "string"
                },
                "workflow": {
                    "type": "string"
                }
            }
        },
        "task.TaskDependsOn": {
            "type": "object",
            "properties": {
                "always": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "success": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "task.TaskLoadStore": {
            "type": "object",
            "properties": {
                "env": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "env_passthrough": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "file": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mounts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "user.APIToken": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "api_tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.APIToken"
                    }
                },
                "created": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "family_name": {
                    "type": "string"
                },
                "given_name": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "login_token": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "reset_token": {
                    "type": "string"
                },
                "reset_token_created": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "workflow.Workflow": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/input.Input"
                    }
                },
                "links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/task.Task"
                    }
                },
                "updated": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Scaffold Swagger API",
	Description:      "Scaffold workflow tool",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
