package constants

const VERSION = "0.1.0"

const STATE_STATUS_ERROR = "error"
const STATE_STATUS_SUCCESS = "success"
const STATE_STATUS_RUNNING = "running"
const STATE_STATUS_WAITING = "waiting"
const STATE_STATUS_NOT_STARTED = "not_started"

const MONGODB_CASCADE_COLLECTION_NAME = "cascade"
const MONGODB_DATASTORE_COLLECTION_NAME = "datastore"
const MONGODB_STATE_COLLECTION_NAME = "state"
const MONGODB_USER_COLLECTION_NAME = "user"
const MONGODB_TASK_COLLECTION_NAME = "task"
const MONGODB_INPUT_COLLECTION_NAME = "input"

const NODE_TYPE_WORKER = "worker"
const NODE_TYPE_MANAGER = "manager"

const COLOR_RED = "\033[0;31m"
const COLOR_YELLOW = "\033[0;33m"
const COLOR_GREEN = "\033[0;32m"
const COLOR_CYAN = "\033[0;36m"
const COLOR_BLUE = "\033[0;34m"
const COLOR_NONE = "\033[0m"
const COLOR_MAGENTA = "\033[0;35m"

const LOG_LEVEL_DEBUG = "DEBUG"
const LOG_LEVEL_ERROR = "ERROR"
const LOG_LEVEL_FATAL = "FATAL"
const LOG_LEVEL_INFO = "INFO"
const LOG_LEVEL_SUCCESS = "SUCCESS"
const LOG_LEVEL_TRACE = "TRACE"
const LOG_LEVEL_WARN = "WARN"

const LOG_LEVEL_DEBUG_NUM = 0
const LOG_LEVEL_ERROR_NUM = 1
const LOG_LEVEL_FATAL_NUM = 2
const LOG_LEVEL_INFO_NUM = 3
const LOG_LEVEL_SUCCESS_NUM = 4
const LOG_LEVEL_TRACE_NUM = 5
const LOG_LEVEL_WARN_NUM = 6

const LOG_FORMAT_JSON = "json"
const LOG_FORMAT_CONSOLE = "console"

const METHOD_GET = COLOR_YELLOW
const METHOD_POST = COLOR_GREEN
const METHOD_PUT = COLOR_BLUE
const METHOD_PATCH = COLOR_CYAN
const METHOD_DELETE = COLOR_RED
