[tool.poetry]
name = "scaffold"
version = "0.4.1"
description = ""
authors = ["John Carter <jfcarter2358@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
